### ISSUE TITLE
 Translations check fails

### ISSUE THREAD

**Issue by open-soft-app** [Bottelet/translation-checker#14]
When the check function (` php artisan translations:check en`) encounters this type of line of code: 
`echo $level == 'error' ? 'Whoops!' : {{trans('email.hello')}}, "\n\n";`

The library fails:
```php
 Error parsing file C:\.......\resources\views\..........\email-plain.blade.php: Syntax error, unexpected '{' on line 6

  at vendor\bottelet\translation-checker\src\Extractor\PhpBaseClassExtractor.php:53
     49▕                 return [];
     50▕             }
     51▕             $traverser->traverse($ast);
     52▕         } catch (Exception $error) {
  ➜  53▕             throw new RuntimeException("Error parsing file {$file->getRealPath()}: {$error->getMessage()}");
     54▕         }
     55▕
     56▕         return array_merge(
     57▕             $this->translationKeys,

  1   vendor\bottelet\translation-checker\src\Finder\MissingKeysFinder.php:26
      Bottelet\TranslationChecker\Extractor\PhpBaseClassExtractor::extractFromFile(Object(SplFileInfo))

  2   vendor\bottelet\translation-checker\src\Finder\MissingKeysFinder.php:49
      Bottelet\TranslationChecker\Finder\MissingKeysFinder::findTranslatableStrings()
```

**Comment by Bottelet** [comment]
Thanks for letting me know! I'll try and fix it over the weekend.

**Comment by Bottelet** [comment]
@open-soft-app Would you mind sending me your entire blade file? 

Having hard time reproducing it, generally seems like some invalid syntax, with echo and the curly brackets?

**Comment by open-soft-app** [comment]
Voilà ;-) This is the file `email-plain.blade.php`:
```php
<?php

if (! empty($greeting)) {
    echo $greeting, "\n\n";
} else {
   echo $level == 'error' ? 'Whoops!' : {{trans('email.hello')}}, "\n\n";
}

if (! empty($introLines)) {
    echo implode("\n", $introLines), "\n\n";
}

if (isset($actionText)) {
    echo "{$actionText}: {$actionUrl}", "\n\n";
}

if (! empty($outroLines)) {
    echo implode("\n", $outroLines), "\n\n";
}

echo 'Regards,', "\n";
echo config('app.name'), "\n";

```

**Comment by Bottelet** [comment]
@open-soft-app I think the main problem lies in this file not being valid blade.php. How do you use this file? I assume it's some email stuff. Perhaps it could just be a .php file without the blade extension?

**Comment by open-soft-app** [comment]
You are right, the file is in the folder "resource/view/vendor/notifications" is generated by "Laravel's vendor:publish" from a very old library to manage emails (my project is in Laravel 11, but the codebase is Laravel 5.1). I don't think anyone uses blade in such a "dirty" way anymore, the bug can be closed in my opinion. Sorry for the "wasted" time.

**Comment by Bottelet** [comment]
No worries! :) Best of luck
