### ISSUE TITLE
translations:find-missing removed all old entries

### ISSUE THREAD

**Issue by rabol** [Bottelet/translation-checker#15]
Hi

I have a en.json with 1330 lines, but after running:

```
php artisan translations:find-missing
```

the file only contains 26 lines and all empty strings

I would have expected the lines to be added :)

**Comment by Bottelet** [comment]
Hi @rabol 

That would also be what is intended, not for it to remove current strings. 

Is it a public repo, that I could check out? I'll see if I can reproduce it over the weekend.

**Comment by Bottelet** [comment]
Thanks, I've downloaded them if you wish to remove them again.

Edit keeps a log, I realized. I'll get back to you.

**Comment by Bottelet** [comment]
Alright, so it all worked when you removed the `.DS_Store`? 

Was the file located in your resources or lang folder?

**Comment by rabol** [comment]
i did not remove the .DS_Store file as that is a file that MacOS will create again.. I added a check in the JsonLanguageFileManager :)

**Comment by Bottelet** [comment]
Make sense. I'm just wondering, because `.DS_Store` file is located in root? And the checker should only be using `lang/` and `resources/` unless other is configured.

**Comment by rabol** [comment]
.DS_Stors is in all folders I think

**Comment by Bottelet** [comment]
@rabol I can't reproduce it. Do you think you would be able to create a PR with a test that fails? So i can try and fix it?

**Comment by rabol** [comment]
I cannot, I will lose and I will do manual comparison using excel or other tool

**Comment by Bottelet** [comment]
I wouldn't want you to lose, totally understandable. best of luck :)
